# This "Book" type can be used in other type declarations.
type Author {
  id: Int
  name: String
  books: [Book]
}

# The "Query" type is the root of all GraphQL queries.
# (A "Mutation" type will be covered later on.)
type Query {
  authors: [Author]
}
